const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const orders = JSON.parse(localStorage.getItem('counterline-orders') || 'null') || [
  { id: '#1086', guest: 'Aarav Menon', items: '2 items', total: 'INR 840', status: 'Preparing', time: '12:42 PM' },
  { id: '#1085', guest: 'Priya Shah', items: '4 items', total: 'INR 1,240', status: 'Ready', time: '12:35 PM' },
  { id: '#1084', guest: 'Dev Patel', items: '1 item', total: 'INR 320', status: 'Pending', time: '12:29 PM' },
  { id: '#1083', guest: 'Meera Rao', items: '3 items', total: 'INR 760', status: 'Completed', time: '12:16 PM' },
  { id: '#1082', guest: 'Kabir Singh', items: '2 items', total: 'INR 580', status: 'Preparing', time: '12:08 PM' }
];
const dishes = [
  { name: 'Butter chicken', sold: '42 sold', price: 'INR 420', category: 'Mains', available: true },
  { name: 'Garlic naan', sold: '38 sold', price: 'INR 160', category: 'Breads', available: true },
  { name: 'Paneer tikka', sold: '31 sold', price: 'INR 360', category: 'Starters', available: true },
  { name: 'Mango lassi', sold: '26 sold', price: 'INR 190', category: 'Drinks', available: false }
];
const pageMeta = { index: ['Good afternoon, Arun', 'Here is what is happening across the floor.'], orders: ['Orders', 'Live queue and completed tickets.'], menu: ['Menu', 'Dishes, pricing, and availability.'], reservations: ['Reservations', 'Upcoming guest bookings.'], reports: ['Reports', 'Performance and trends.'] };
function toast(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2600); }
function saveOrders() { localStorage.setItem('counterline-orders', JSON.stringify(orders)); }
function renderOrders(list = orders, target = $('#orderRows')) { if (!target) return; target.innerHTML = list.map(order => `<div class="order-row"><span class="order-id">${order.id}</span><strong class="order-customer">${order.guest}</strong><span class="order-items">${order.items}</span><strong>${order.total}</strong><span class="order-time">${order.time || 'Now'}</span><span class="status ${order.status.toLowerCase()}">${order.status}</span></div>`).join('') || '<div class="empty-state"><p>No matching orders.</p></div>'; }
function renderDishes(target = $('#dishRows')) { if (!target) return; target.innerHTML = dishes.map((dish, index) => `<div class="dish-row"><div class="dish-avatar">${['+','o','*','~'][index]}</div><div><strong>${dish.name}</strong><small>${dish.sold} | ${dish.category}</small></div><span class="dish-price">${dish.price}</span></div>`).join(''); }
function openModal() { const modal = $('#modalBackdrop'); if (modal) { modal.classList.add('show'); $('#guestName')?.focus(); } }
function closeModal() { const modal = $('#modalBackdrop'); if (modal) { modal.classList.remove('show'); $('#orderForm')?.reset(); } }
function initNavigation() { const current = location.pathname.split('/').pop() || 'index.html'; $$('.nav a').forEach(link => link.classList.toggle('active', link.getAttribute('href') === current)); $('#menuToggle')?.addEventListener('click', () => $('#sidebar')?.classList.toggle('open')); $('#themeToggle')?.addEventListener('click', () => { document.body.classList.toggle('night'); localStorage.setItem('counterline-night', document.body.classList.contains('night')); toast('Theme preference updated'); }); if (localStorage.getItem('counterline-night') === 'true') document.body.classList.add('night'); $('#notificationToggle')?.addEventListener('click', () => $('#notifications')?.classList.toggle('show')); $('#clearNotifications')?.addEventListener('click', () => { $('#notifications')?.classList.remove('show'); toast('Service notes marked as read'); }); $('#logout')?.addEventListener('click', () => toast('Signed out of demo mode')); }
function initGlobalSearch() { $('#globalSearch')?.addEventListener('input', event => { const query = event.target.value.toLowerCase(); renderOrders(orders.filter(order => `${order.id} ${order.guest} ${order.items} ${order.status}`.toLowerCase().includes(query))); }); }
function initOrderModal() { $('#newOrder')?.addEventListener('click', openModal); $('#openOrderModal')?.addEventListener('click', openModal); $('#closeModal')?.addEventListener('click', closeModal); $('#cancelModal')?.addEventListener('click', closeModal); $('#modalBackdrop')?.addEventListener('click', event => { if (event.target.id === 'modalBackdrop') closeModal(); }); $('#orderForm')?.addEventListener('submit', event => { event.preventDefault(); const total = Number($('#orderTotal').value || 0).toLocaleString('en-IN'); orders.unshift({ id: `#${1087 + orders.length}`, guest: $('#guestName').value, items: $('#orderItems').value, total: `INR ${total}`, status: 'Pending', time: 'Just now' }); saveOrders(); renderOrders(); closeModal(); toast('Order added to the live queue'); }); }
function initPageActions() { $$('.action-button').forEach(button => button.addEventListener('click', () => toast(button.dataset.message || 'Action completed'))); $('#exportSales')?.addEventListener('click', () => toast('Sales report exported as CSV')); $('#rangeSelect')?.addEventListener('change', event => toast(`Showing ${event.target.value.toLowerCase()}`)); $$('.filter-button').forEach(button => button.addEventListener('click', () => { $$('.filter-button').forEach(item => item.classList.remove('active')); button.classList.add('active'); const state = button.dataset.status; renderOrders(state ? orders.filter(order => order.status.toLowerCase() === state) : orders, $('#ordersTable')); })); $$('.availability-toggle').forEach(toggle => toggle.addEventListener('click', () => { toggle.textContent = toggle.textContent === 'Available' ? 'Paused' : 'Available'; toggle.classList.toggle('paused'); toast(`Dish ${toggle.textContent.toLowerCase()}`); })); }
function initCharts() { if (!window.Chart || !$('#salesChart')) return; new Chart($('#salesChart'), { type: 'line', data: { labels: ['10a','11a','12p','1p','2p','3p','4p','5p','6p'], datasets: [{ data: [4,8,12,19,16,13,22,28,25], borderColor: '#e88832', backgroundColor: 'rgba(232,136,50,.12)', fill: true, tension: .38, pointRadius: 3, pointBackgroundColor: '#fffef9', pointBorderWidth: 2, pointBorderColor: '#e88832' }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { displayColors: false, callbacks: { label: context => ` INR ${context.parsed.y}k` } } }, scales: { y: { beginAtZero: true, border: { display: false }, grid: { color: '#eef0e8' }, ticks: { font: { family: 'DM Mono', size: 9 }, callback: value => `INR ${value}k` } }, x: { border: { display: false }, grid: { display: false }, ticks: { font: { family: 'DM Mono', size: 9 } } } } } }); }
function boot() { initNavigation(); initGlobalSearch(); initOrderModal(); initPageActions(); renderOrders(); renderDishes(); initCharts(); if (window.lucide) lucide.createIcons(); }
document.addEventListener('DOMContentLoaded', boot);
